// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Rebound_GPGSIds
{
        public const string achievement_welcome_to_rebound = "CgkImqbwrIMTEAIQAg"; // <GPGSID>
        public const string achievement_getting_started = "CgkImqbwrIMTEAIQAw"; // <GPGSID>
        public const string achievement_now_you_lose_more_time = "CgkImqbwrIMTEAIQBQ"; // <GPGSID>
        public const string achievement_you_cant_miss_now = "CgkImqbwrIMTEAIQBw"; // <GPGSID>
        public const string achievement_youre_still_going = "CgkImqbwrIMTEAIQBg"; // <GPGSID>
        public const string achievement_now_youre_getting_it = "CgkImqbwrIMTEAIQBA"; // <GPGSID>
        public const string leaderboard_timed_mode = "CgkImqbwrIMTEAIQAQ"; // <GPGSID>
        public const string achievement_what_a_pro = "CgkImqbwrIMTEAIQCA"; // <GPGSID>

}

